'use client';
import { useEffect, useState } from 'react';
import { flushSync } from 'react-dom';
import { calculateQuote, type MeterId } from '@/lib/pricing';
import { ArrowUpRight, ArrowRight, Check, ShieldCheck, Printer, RefreshCw, Headphones, Plus, Zap, CreditCard, BarChart3, Download, ShoppingBag } from 'lucide-react';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const meters=[{id:'mini',name:'M2 Mini',tag:'PIENI KOKO. TÄYSI TEHO.',desc:'Kompakti mittari, joka löytää paikkansa jokaisesta autosta.',base:75},{id:'touch',name:'M2 Touch',tag:'KAIKKI KOSKETUKSEN PÄÄSSÄ.',desc:'Selkeä kosketusnäyttö sujuvaan ammattiajoon.',base:85},{id:'mirror',name:'M2 Peilitaksamittari',tag:'HUOMAAMATTOMAN TYYLIKÄS.',desc:'Peiliin integroitu mittari viimeisteltyyn ohjaamoon.',base:95}];
const euro=(n:number)=>n.toLocaleString('fi-FI',{minimumFractionDigits:n%1?2:0,maximumFractionDigits:2});
export default function Home(){
 const [period,setPeriod]=useState(12),[meter,setMeter]=useState('touch'),[mpos,setMpos]=useState(false),[dispatch,setDispatch]=useState('none'),[extra,setExtra]=useState(false),[checkout,setCheckout]=useState(false),[downloaded,setDownloaded]=useState(false);
 const selected=meters.find(m=>m.id===meter)!;const {discount,price,dispatchPrice,monthly,total}=calculateQuote({meter:meter as MeterId,period,mpos,dispatch,extra});
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'configure_taxi_package',title:'Configure TaxaOn package',description:'Select a meter, contract duration and accessories. Updates the visible quote; does not place an order.',inputSchema:{type:'object',properties:{meter:{type:'string',enum:['mini','touch','mirror']},period:{type:'number',enum:[6,12,24]},mpos:{type:'boolean'},dispatch:{type:'string',enum:['none','phone','tablet']},extra:{type:'boolean'}},required:['meter','period','mpos','dispatch','extra'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(raw:unknown)=>{if(!raw||typeof raw!=='object')throw new Error('Expected package configuration');const input=raw as Parameters<typeof calculateQuote>[0];const quote=calculateQuote(input);flushSync(()=>{setMeter(input.meter);setPeriod(input.period);setMpos(input.mpos);setDispatch(input.dispatch);setExtra(input.extra)});return {...quote,currency:'EUR',vat:'excluded',orderPlaced:false}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[]);
 function download(){const blob=new Blob([`TaxaOn — tilausluonnos\n${selected.name} ja kirjoitin\nSopimus: ${period} kk\nMittari: ${euro(price)} €/kk\nSemel mPOS: ${mpos?'34 €/kk':'Ei'}\nAjovälityspääte: ${dispatch} (${euro(dispatchPrice)} €/kk)\nVuoro.NET: ${extra?'EXTRA 8,20 €/kk':'BASIC sisältyy'}\nYhteensä: ${euro(monthly)} €/kk\nKäsittelymaksu: 150 €\nSopimuskausi yhteensä: ${euro(total)} €\nALV 0 %. Alustava hinnoittelu. Tämä on tilausluonnos, jota ei ole lähetetty.\n`],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='TaxaOn-tilausluonnos.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setDownloaded(true)}
 return <><header className="header"><a href="#" className="brand">Taxa<span>On</span><i/></a><nav><a className="active" href="#meters">Rakenna pakettisi</a><a href="#included">Mitä hintaan kuuluu?</a></nav><a className="help" href="https://semel.fi/verkkokauppa/" target="_blank" rel="noreferrer"><Headphones size={17}/> Tarvitsetko apua? <ArrowUpRight size={15}/></a></header>
 <main><section className="intro"><div><p className="eyebrow"><span/> VALMIINA SEURAAVAAN VUOROON</p><h1>Sinun taksisi.<br/>Sinun <span>tapasi ajaa.</span></h1><p className="lead">Valitse mittari, lisävarusteet ja sopimuskausi.<br/>Yksi selkeä kuukausihinta. Kaikki omilla ehdoillasi.</p></div><div className="intro-aside"><div className="signal"><Zap size={22}/><span>Vähemmän säätöä.<br/><strong>Enemmän ajoa.</strong></span></div><p>SEMEL-TEKNOLOGIA <span>×</span> TAXAON-JOUSTAVUUS</p></div></section>
 <div className="shop-layout"><div className="configuration"><section className="period-section"><div className="section-heading"><h2><span>01</span> Valitse sopimuskausi</h2><p>Pidempi sopimus, pienempi kuukausihinta.</p></div><RadioGroup className="periods" value={String(period)} onValueChange={v=>setPeriod(Number(v))} aria-label="Sopimuskausi">{[6,12,24].map(p=><label key={p} className={`period ${period===p?'chosen':''}`}><RadioGroupItem value={String(p)} aria-label={`${p} kuukautta`}/><div><strong>{p} <small>kuukautta</small></strong><p>{p===6?'Enemmän joustoa':p===12?'Sopivasti sitoutumista':'Paras kuukausihinta'}</p></div>{p!==6&&<span className="saving">−{p===12?10:20} € / kk</span>}</label>)}</RadioGroup></section>
 <section id="meters"><div className="section-heading"><h2><span>02</span> Löydä oma mittarisi</h2><p>Kirjoitin kuuluu jokaiseen pakettiin.</p></div><RadioGroup value={meter} onValueChange={v=>setMeter(String(v))} className="meters" aria-label="Taksamittari">{meters.map(m=><label key={m.id} className={`meter ${meter===m.id?'selected':''}`}><div className="card-top"><span>{m.id==='touch'?'SUOSITTU VALINTA':'SEMEL M2'}</span><RadioGroupItem value={m.id} aria-label={m.name}/></div><div className="product-image"><img src={`/products/${m.id}.jpg`} alt={`Semel ${m.name} ja kirjoitin`}/></div><div className="product-copy"><p className="product-tag">{m.tag}</p><h3>{m.name}</h3><p className="product-desc">{m.desc}</p><div className="price-row"><strong>{m.base-discount} €<small> / kk</small></strong>{discount>0&&<s>{m.base} €</s>}</div><div className="selection">{meter===m.id?<><Check size={15}/> Valittu paketti</>:<>Valitse mittari <Plus size={16}/></>}</div></div></label>)}</RadioGroup></section>
 <section id="accessories"><div className="section-heading"><h2><span>03</span> Täydennä kokonaisuus</h2><p>Vain se, mitä tarvitset.</p></div><div className="accessory-grid"><label className={`accessory ${mpos?'on':''}`}><CreditCard/><div><strong>Semel mPOS</strong><p>Maksupääte</p></div><b>+34 €<small>/ kk</small></b><Checkbox checked={mpos} onCheckedChange={setMpos} aria-label="Lisää Semel mPOS"/></label><label className={`accessory ${extra?'on':''}`}><BarChart3/><div><strong>Vuoro.NET EXTRA</strong><p>Laajempi raportointi</p></div><b>+8,20 €<small>/ kk</small></b><Checkbox checked={extra} onCheckedChange={setExtra} aria-label="Lisää Vuoro.NET EXTRA"/></label></div><div className="dispatch-heading">Ajovälityspääte <span>Valitse yksi vaihtoehto</span></div><RadioGroup value={dispatch} onValueChange={v=>setDispatch(String(v))} className="dispatch-options" aria-label="Ajovälityspääte">{[{id:'none',name:'Ei päätettä',description:'Käytän omaa ratkaisua',cost:0},{id:'phone',name:'Contact Phone',description:'Samsung Xcover 7',cost:43},{id:'tablet',name:'Contact Tablet',description:'Galaxy Tab Active5',cost:61}].map(d=><label key={d.id} className={dispatch===d.id?'on':''}><RadioGroupItem value={d.id} aria-label={d.name}/>{d.id!=='none'&&<img src={`/products/${d.id}.jpg`} alt={d.name}/>}<div><strong>{d.name}</strong><small>{d.description}</small></div><b>{d.cost?`+${d.cost} €`:'0 €'}</b></label>)}</RadioGroup></section>
 <section id="included" className="included"><h3>Enemmän kuin pelkkä mittari.</h3><div><span><Printer/> Kirjoitin</span><span><BarChart3/> Vuoro.NET BASIC</span><span><RefreshCw/> Ohjelmistopäivitykset</span><span><ShieldCheck/> Takuu ja vaihtolaitepalvelu</span></div></section></div>
 <aside className="summary"><div className="summary-heading"><h2>Sinun ajopakettisi</h2><ShoppingBag size={19}/></div><div className="summary-product"><img src={`/products/${meter}.jpg`} alt={selected.name}/><div><small>SEMEL</small><strong>{selected.name}</strong><span>Taksamittari + kirjoitin</span></div></div><div className="contract-chip"><span>Sopimuskausi</span><strong>{period} kuukautta</strong></div><div className="line"><span>{selected.name}</span><b>{euro(price)} €</b></div><div className="line"><span>Vuoro.NET {extra?'EXTRA':'BASIC'}</span><b>{extra?'8,20 €':'Sisältyy'}</b></div>{mpos&&<div className="line"><span>Semel mPOS</span><b>34 €</b></div>}{dispatch!=='none'&&<div className="line"><span>Contact {dispatch==='phone'?'Phone':'Tablet'}</span><b>{dispatchPrice} €</b></div>}<div className="total" aria-live="polite" aria-atomic="true"><span>Kuukausihinta</span><strong>{euro(monthly)} €<small>/ kk</small></strong><p>Hinnat alv 0 %</p></div>{discount>0&&<div className="savings-note"><Zap size={17}/><span>Säästät <b>{discount*period} €</b> sopimuskaudella<small>Verrattuna 6 kk:n kuukausihintaan</small></span></div>}<div className="line fee"><span>Kertamaksu alussa</span><b>150 €</b></div><div className="line"><span>Sopimuskausi yhteensä</span><b>{euro(total)} €</b></div><button className="cta" onClick={()=>{setDownloaded(false);setCheckout(true)}}>Jatka tilaukseen <ArrowRight size={19}/></button><p className="summary-foot">Tarkista kokonaisuus seuraavassa vaiheessa.</p><div className="note"><ShieldCheck size={17}/><p>SIM-kortti hankitaan erikseen. Tarkista ajovälityspäätteen yhteensopivuus oman välitysyhtiösi kanssa.</p></div></aside></div>
 <footer><a href="#" className="brand">Taxa<span>On</span><i/></a><p>Valmiina ajoon. Omilla ehdoillasi.</p><a href="https://semel.fi/verkkokauppa/" target="_blank" rel="noreferrer">Tuotetiedot ja kuvat: Semel <ArrowUpRight size={14}/></a><small>Esittelykauppa · Alustava hinnoittelu</small></footer></main>
 <Dialog open={checkout} onOpenChange={setCheckout}><DialogContent className="checkout"><DialogTitle>Tarkista tilausluonnos</DialogTitle><DialogDescription>Esittelykauppa: tilauksia ei vielä lähetetä. Voit tallentaa valitsemasi kokonaisuuden.</DialogDescription><div className="review"><strong>{selected.name} + kirjoitin</strong><p>{period} kuukauden sopimus</p><p>Vuoro.NET {extra?'EXTRA':'BASIC'}{mpos?' · Semel mPOS':''}{dispatch!=='none'?` · Contact ${dispatch==='phone'?'Phone':'Tablet'}`:''}</p><h3>{euro(monthly)} € / kk</h3><p>Kertamaksu 150 € · Yhteensä {euro(total)} € (alv 0 %)</p></div><p className="muted">TaxaOnin sopimuskausien hinnat ovat alustavia. SIM-kortti ei sisälly. Asennuksen saatavuus ja hinta vahvistetaan erikseen.</p><button className="cta" onClick={download}><Download size={18}/> Lataa tilausluonnos</button>{downloaded&&<p role="status">Tilausluonnos ladattu. Tilausta ei ole lähetetty.</p>}</DialogContent></Dialog></>;
}
